services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: tinyurl-php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: tinyurl-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: tinyurl-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
